<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>monk</string>
	</array>
	<key>name</key>
	<string>Monkberry</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Since html is valid in Monkberry templates include the html patterns</string>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>variable.other.monkberry.template</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>({%)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.monkberry.tagbraces</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(%})</string>
			<key>name</key>
			<string>meta.scope.monkberry.template.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(for|of|endfor|if|else|endif|import|from|block|endblock|unsafe)\b</string>
					<key>name</key>
					<string>keyword.control.monkberry.template</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(of|from)\b</string>
					<key>name</key>
					<string>keyword.operator.monkberry.template</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>('|")</string>
					<key>end</key>
					<string>\1</string>
					<key>name</key>
					<string>string.other.monkberry.template.tag</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]+</string>
					<key>name</key>
					<string>string.unquoted.monkberry.template.tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.monkberry</string>
</dict>
</plist>
